---
title: "p8105_hw2_yl5219"
author: "Yuqing Liu"
date: "2023-09-27"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=FALSE}
library(tidyverse)
```

# Problem 1
import three datasets:
```{r import data}
pols_month = read.csv(file = "./fivethirtyeight_datasets/pols-month.csv")
unemployment = read.csv(file = "./fivethirtyeight_datasets/unemployment.csv")
snp = read.csv(file = "./fivethirtyeight_datasets/snp.csv")
```

clean the data in pols-month:
```{r import and clean pols-month.csv dataset}
pols_month = read.csv(file = "./fivethirtyeight_datasets/pols-month.csv") |> janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"))|>
  mutate(
    month =
      case_match(
        month,
        "01" ~ "jan",
        "02" ~ "feb",
        "03" ~ "mar",
        "04" ~ "apr",
        "05" ~ "may",
        "06" ~ "jun",
        "07" ~ "jul",
        "08" ~ "aug",
        "09" ~ "sep",
        "10" ~ "oct",
        "11" ~ "nov",
        "12" ~ "dec")
      )|>
  mutate(president=case_match(
           prez_dem,
           1~"democratic",
           0~"republican"))  |>
  select(-prez_dem, -prez_gop, -day)

pols_month
```



clean the data in snp:
```{r import and clean snp.csv dataset}
snp = read.csv(file = "./fivethirtyeight_datasets/snp.csv")|>
  janitor::clean_names()|>
  separate(date, into = c("month", "day", "year"))|>
  mutate(
    month =
      case_match(
        month,
        "1" ~ "jan",
        "2" ~ "feb",
        "3" ~ "mar",
        "4" ~ "apr",
        "5" ~ "may",
        "6" ~ "jun",
        "7" ~ "jul",
        "8" ~ "aug",
        "9" ~ "sep",
        "10" ~ "oct",
        "11" ~ "nov",
        "12" ~ "dec")
      )|>select(-day)|>
  select(year, month, everything())

snp
```

clean the data in unemployment:
```{r import and clean unemployment.csv dataset}
unemployment = read.csv(file = "./fivethirtyeight_datasets/unemployment.csv")|>
  janitor::clean_names()|>
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment")|>
    mutate(year=as.character(year))

unemployment
```

join the datasets:
```{r}
df=pols_month|>
  left_join(snp,by=c("year", "month"))|>
  left_join(unemployment, by=c("year", "month"))

df
```



